<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:tns="http://module.Framework.Shared.Resources.ServiceDescriptors.EAI.Exception.Handling.success.1.0/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="EAI.Exception.Handling.success.1.0" targetNamespace="http://module.Framework.Shared.Resources.ServiceDescriptors.EAI.Exception.Handling.success.1.0/" xmlns:xsd1="http://ns.corelio.be/common/envelope/1.0" xmlns:xsd2="http://ns.corelio.be/common/in/1.0">
    <wsdl:types>
    

    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    	<xsd:import namespace="http://ns.corelio.be/common/envelope/1.0"
    		schemaLocation="../Schemas/Logging/CommonTypes.xsd">
    	</xsd:import>
    	<xsd:import namespace="http://ns.corelio.be/common/in/1.0"
    		schemaLocation="../Schemas/Logging/In.xsd">
    	</xsd:import></xsd:schema></wsdl:types>
    <wsdl:message name="OperationRequest">
        <wsdl:part name="parameters" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="OperationResponse">
     
        <wsdl:part name="parameters" type="xsd1:Result"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="EAI.Exception.Handling.success.1.0">
        <wsdl:operation name="Operation">
            <wsdl:input message="tns:OperationRequest"/>
            <wsdl:output message="tns:OperationResponse"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
