<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:tns="http://EAI/MDS/GetConfig/1/0/" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
name="EAI.MDS.GetConfig.1.0" 
targetNamespace="http://EAI/MDS/GetConfig/1/0/" 
xmlns:xsd1="http://ns.corelio.be/mds/EntityMembers.xsd">


   
  <wsdl:types>
  	<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  		<xsd:import
  			namespace="http://ns.corelio.be/mds/EntityMembers.xsd"
  			schemaLocation="../Schemas/Resources/MDSEntityMembers.xsd">
  		</xsd:import></xsd:schema></wsdl:types>
  <wsdl:message name="OperationRequest">
    <wsdl:part name="parameters" element="xsd1:QueryRequest"/>
  </wsdl:message>
  <wsdl:message name="OperationResponse">
    <wsdl:part element="xsd1:QueryResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="EAI.MDS.GetConfig.1.0">
    <wsdl:operation name="Operation">
      <wsdl:input message="tns:OperationRequest"/>
      <wsdl:output message="tns:OperationResponse"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
