<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:tns="http://EAI/SharedResources/CallServiceMultiThread/1/0/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
name="EAI.SharedResources.CallServiceMultiThread.1.0" 
targetNamespace="http://EAI/SharedResources/CallServiceMultiThread/1/0/" 
xmlns:xsd1="http://Polarising/SharedResources/Schemas/EAIMessaging/MultiThreadService"> 

  <wsdl:types>
  <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  	<xsd:import
  		namespace="http://Polarising/SharedResources/Schemas/EAIMessaging/MultiThreadService"
  		schemaLocation="../Schemas/EAIMessaging/MultiThreadService.xsd">
  	</xsd:import>
  	<xsd:import namespace="http://ns.corelio.be/common/logical/1.0"
  		schemaLocation="../Schemas/EAIMessaging/Logical.xsd">
  	</xsd:import></xsd:schema></wsdl:types>
  <wsdl:message name="OperationRequest">
    <wsdl:part element="xsd1:MultiThreadIn" name="parameters" />
  </wsdl:message>
  <wsdl:message name="OperationResponse">
    <wsdl:part element="xsd1:MultiThreadOut" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="EAI.SharedResources.CallServiceMultiThread.1.0">
    <wsdl:operation name="Operation">
      <wsdl:input message="tns:OperationRequest"/>
      <wsdl:output message="tns:OperationResponse"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
